### ISSUE TITLE
Fixed camera position multiple players

### ISSUE THREAD

**Issue by jightya** [emlun/factorio-replay-timelapse#2]
Hello, thanks for youre work! Trying to use it, the screenshots it saves are all from the same position. eventho it shouldnt been from a multiplayer safe with 3 people.

any advice?

**Comment by emlun** [comment]
Hi! I'm not sure what you mean is wrong - the camera is programmed to track buildings and building ghosts, not the player character (or characters). The camera zooms out to cover and center all player buildings on the map as well as possible, but there's a limit to how far the camera can feasibly zoom out while keeping things identifiable. After that point the camera instead switches to tracking everything built in the last 2 timelapse seconds, and if it can't do that either, it just stays where it is. Maybe that's what's happening if you have multiple people off building in different locations.

There are other camera placement strategies that would be possible, like the TLBE mod which lets you set multiple cameras tracking different things, but I haven't added anything like that to this tool because it's not something I've needed myself (and it takes a lot of time to test...). As of now, this tool only has the one camera placement strategy described in the previous paragraph.

**Comment by jightya** [comment]
Yes you are right. I was being dumb lol. Thank you for youre reply. I have 1 more question, how do i save the screenshots to an other drive? i tried changing this :

local output_dir = "replay-timelapse"    -- Output directory (relative to Factorio script output directory)

to this:

local output_dir = "D:/MBTimelapseScreenshots"    -- Output directory (relative to Factorio script output directory)

but it doesnt work, pretty sure i am just to noob to figure out the syntax, but if you could tell me, that would greatly be appreciated.

**Comment by emlun** [comment]
No worries. 🙂

> how do i save the screenshots to an other drive?

That's not possible, Factorio only allows scripts to output screenshot files within the `script-output` directory. The only way to do it is to mount the target drive as a subdirectory within that, or create a symbolic file system link, if your file system supports either of those (both are easy to do with most Linux file systems, but a bit more involved in NTFS I think).

**Comment by jightya** [comment]
Thanks for youre anwser. i geuss i will just have robocopy run every x minutes with /mov. because of disk space :P

appreciate youre time and work!

**Comment by jightya** [comment]
appreciate youre time and work! closed since its all resolved
